const TYPE_CODE = {
  FOR_POST: {
    HOUSE: "HOUSE",
    APARTMENT: "APARTMENT",
    OFFICE: "OFFICE",
    BUSSINESS_PREMISES: "BUSSINESS_PREMISES",
    MOTEL: "MOTEL",
    LAND: "LAND",
    OTHERS: "OTHERS"
  },
  CODE_VIP: {
    X_NORMAL: "X_NORMAL",
    VIP_S0: "VIP_S0",
    VIP_S1: "VIP_S1",
    VIP_S2: "VIP_S2"
  },
  FILE_UPLOAD: {
    PROPERTY_IMAGES_FRONTSIDE: "PROPERTY_IMAGES_FRONTSIDE",
    PROPERTY_IMAGES_WAYIN: "PROPERTY_IMAGES_WAYIN",
    PROPERTY_IMAGES_FURNITURES: "PROPERTY_IMAGES_FURNITURES",
    PROPERTY_IMAGES_OTHERS: "PROPERTY_IMAGES_OTHERS",
    PROPERTY_VIDEOSPERTY_DOCUMENTS_FRONT: "PROPERTY_VIDEOSPERTY_DOCUMENTS_FRONT",
    PROPERTY_DOCUMENTS_BACK: "PROPERTY_DOCUMENTS_BACK",
    PROPERTY_DOCUMENTS_SIGNATURE: "PROPERTY_DOCUMENTS_SIGNATURE",
    PROPERTY_DOCUMENTS_MARK: "PROPERTY_DOCUMENTS_MARK",
    PROPERTY_DETAILS_FLOORS_ROOMSIMAGES: "PROPERTY_DETAILS_FLOORS_ROOMSIMAGES",
    PROPERTY_DETAILS_FLOORS_BATHROOMSIMAGES: "PROPERTY_DETAILS_FLOORS_BATHROOMSIMAGES",
    PROPERTY_DETAILS_FLOORS_VIDEOS: "PROPERTY_DETAILS_FLOORS_VIDEOS"
  }
}

export default TYPE_CODE
