export const SIGN_IN = "SIGN_IN"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"

export const SIGN_UP = "SIGN_UP"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"

export const GET_CITY = "GET_CITY"
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS"
export const GET_CITY_FAILURE = "GET_CITY_FAILURE"

export const GET_DISTRICT = "GET_DISTRICT"
export const GET_DISTRICT_SUCCESS = "GET_DISTRICT_SUCCESS"
export const GET_DISTRICT_FAILURE = "GET_DISTRICT_FAILURE"

export const GET_WARD = "GET_WARD"
export const GET_WARD_SUCCESS = "GET_WARD_SUCCESS"
export const GET_WARD_FAILURE = "GET_WARD_FAILURE"

export const GET_STREET = "GET_STREET"
export const GET_STREET_SUCCESS = "GET_STREET_SUCCESS"
export const GET_STREET_FAILURE = "GET_STREET_FAILURE"

export const OPEN_HUD = "OPEN_HUD"
export const CLOSE_HUD = "CLOSE_HUD"

export const GET_PRODUCT_TYPE = "GET_PRODUCT_TYPE"
export const GET_PRODUCT_CATE = "GET_PRODUCT_CATE"
export const GET_PRICE_UNIT = "GET_PRICE_UNIT"
export const GET_AREA = "GET_AREA"
export const GET_PRICE = "GET_PRICE"

export const OPEN_SELECT_TYPE_POST = "OPEN_SELECT_TYPE_POST"
export const CLOSE_SELECT_TYPE_POST = "CLOSE_SELECT_TYPE_POST"

export const FETCH_POST_FOR_SALE_HOME = "FETCH_POST_FOR_SALE_HOME"
export const FETCH_POST_FOR_SALE_HOME_SUCCESS =
  "FETCH_POST_FOR_SALE_HOME_SUCCESS"

export const FETCH_POST_FOR_RENT_HOME = "FETCH_POST_FOR_RENT_HOME"
export const FETCH_POST_FOR_RENT_HOME_SUCCESS =
  "FETCH_POST_FOR_RENT_HOME_SUCCESS"
